defmodule NepeanCircular.Repo.Migrations.AddSubscribers do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:subscribers, primary_key: false) do
      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :unsubscribed_at, :utc_datetime
      add :token, :text, null: false
      add :email, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create unique_index(:subscribers, [:email], name: "subscribers_unique_email_index")
  end

  def down do
    drop_if_exists unique_index(:subscribers, [:email], name: "subscribers_unique_email_index")

    drop table(:subscribers)
  end
end
