defmodule NepeanCircular.Repo.Migrations.AddStoreUniqueName do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create unique_index(:stores, [:name], name: "stores_unique_name_index")
  end

  def down do
    drop_if_exists unique_index(:stores, [:name], name: "stores_unique_name_index")
  end
end
