defmodule NepeanCircular.Repo.Migrations.AddWelcomedAt do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:subscribers) do
      add :welcomed_at, :utc_datetime
    end
  end

  def down do
    alter table(:subscribers) do
      remove :welcomed_at
    end
  end
end
