defmodule NepeanCircular.Repo.Migrations.InitialSetup do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:stores, primary_key: false) do
      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :active, :boolean
      add :logo_url, :text
      add :scraper_module, :text, null: false
      add :url, :text, null: false
      add :name, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create table(:flyers, primary_key: false) do
      add :store_id, references(:stores, column: :id, name: "flyers_store_id_fkey", type: :uuid),
        null: false

      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :scraped_at, :utc_datetime_usec, null: false
      add :valid_to, :date
      add :valid_from, :date
      add :pdf_url, :text, null: false
      add :title, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create unique_index(:flyers, [:pdf_url], name: "flyers_unique_pdf_url_index")
  end

  def down do
    drop_if_exists unique_index(:flyers, [:pdf_url], name: "flyers_unique_pdf_url_index")

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `flyers` table without the `flyers_store_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    drop table(:flyers)

    drop table(:stores)
  end
end
